version: '3'

services:
    app:
        build: .
        container_name: ip4y-app
        volumes:
            - .:/var/www
            - ./.docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        networks:
            - ip4y-network
        depends_on:
            - db

    nginx:
        build: .docker/nginx
        container_name: ip4y-nginx
        restart: always
        tty: true
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
        networks:
            - ip4y-network
        depends_on:
            - app

    db:
        build: ./.docker/mysql
        container_name: ip4y-db
        restart: always
        tty: true
        ports:
            - "33006:3306"
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
            - ./.docker/mysql:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_DATABASE=ip4y
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - ip4y-network

networks:
    ip4y-network:
        driver: bridge
